using System;
using Microsoft.EntityFrameworkCore;
using ShreenexTech.API.Domain.Entities;

namespace ShreenexTech.API.Infrastructure.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options)
            : base(options)
        {
        }

        // existing Portfolio property kept (matches existing usage)
        public DbSet<Portfolio> Portfolio { get; set; }

        // Add DbSets for all models
        public DbSet<TeamMember> TeamMembers { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<NewsletterSubscriber> NewsletterSubscribers { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<JobApplication> JobApplications { get; set; }
        public DbSet<ContactMessage> ContactMessages { get; set; }
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Admin> Admins { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Job -> JobApplications (one-to-many)
            modelBuilder.Entity<JobApplication>()
                .HasOne(ja => ja.Job)
                .WithMany(j => j.Applications)
                .HasForeignKey(ja => ja.JobId)
                .OnDelete(DeleteBehavior.Cascade);

            // Ensure CreatedDate is generated by DB with GETDATE()
            modelBuilder.Entity<Portfolio>()
                .Property(p => p.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("GETDATE()")
                .ValueGeneratedOnAdd();

            // Example: unique index on Admin.Email
            modelBuilder.Entity<Admin>()
                .HasIndex(a => a.Email)
                .IsUnique();

            // Optional: ensure table names are respected (attributes already applied)
        }
    }
}
